#pragma once

#include <string>
using std::string;
using uint = unsigned int;

// Tipos que devem ser disponibilizados na tabela de síntese da saída
enum tipos {
    CLASSE, RELACAO, PALAVRASCHAVE, INSTANCIAS, PALAVRASRESERVADAS, METAATRIBUTOS
};

// Tipos que os lexemas podem assumir
enum tokenTipos {
    GENSET=1, DISJOINT, COMPLETE, GENERAL, SPECIFICS, WHERE, PACKAGE, IMPORT, FUNCTIONAL_COMPLEXES, 

    EVENT, SITUATION, PROCESS, CATEGORY, MIXIN, PHASEMIXIN, ROLEMIXIN, HISTORICALMIXIN, KIND, 
    COLLECTIVE, QUANTITY, QUALITY, MODE, INTRISICMODE, EXTRINSINCMODE, SUBKIND, PHASE, ROLE, 
    HISTORICALROLE, 

    MATERIAL, DERIVATION, COMPARATIVE, MEDIATION, CHARACTERIZATION, EXTERNALDEPENDENCE, 
    COMPONENTOF, MEMBEROF, SUBCOLLECTIONOF, SUBQUALITYOF, INSTANTIATION, TERMINATION, PARTICIPATIONAL, 
    PARTICIPATION, HISTORICALDEPENDENCE, CREATION, MANIFESTATION, BRINGSABOUT, TRIGGERS, COMPOSITION, 
    AGGREGATION, INHERENCE, VALUE, FORMAL, CONTITUTION, 

    ORDERED, CONST, DERIVED, SUBSETS, REDEFINES,

    NUMBER, STRING, BOOLEAN, DATE, TIME, DATETIME,

    NUMBERLITERAL, ESPECIALSYMBOL, NEWTYPE, INSTANCENAME, CLASSNAME, RELATIONAME
};

// O token em si
struct token {
    uint tipo;
    string lexema;
    int linha;
    int coluna;
};