#pragma once

#include <string>
using std::string;
using uint = unsigned int;

// Classificação dos tokens que devem ser disponibilizados na tabela de síntese da saída.
enum tokenClassification {
    RESERVED_WORDS, META_ATTRIBUTES, CLASS_STEREOTYPE, RELATION_STEREOTYPE, KEY_WORDS, INSTANCES
};

// Tipos que os token podem assumir.
enum tokenTypes {
    GENSET=0, DISJOINT, COMPLETE, GENERAL, SPECIFICS, WHERE, PACKAGE, IMPORT, FUNCTIONAL_COMPLEXES, 

    NUMBER, STRING, BOOLEAN, DATE, TIME, DATETIME,

    ORDERED, CONST, DERIVED, SUBSETS, REDEFINES,

    EVENT, SITUATION, PROCESS, CATEGORY, MIXIN, PHASE_MIXIN, ROLE_MIXIN, HISTORICAL_MIXIN, 
    HISTORICAL_ROLE, HISTORICAL_ROLE_MIXIN, KIND, COLLECTIVE, QUANTITY, QUALITY, MODE, 
    INTRINSIC_MODE, EXTRINSIC_MODE, SUBKIND, PHASE, ROLE, 
    
    MATERIAL, DERIVATION, COMPARATIVE, MEDIATION, CHARACTERIZATION, EXTERNAL_DEPENDENCE, 
    COMPONENT_OF, MEMBER_OF, SUB_COLLECTION_OF, SUB_QUALITY_OF, INSTANTIATION, TERMINATION, PARTICIPATIONAL, 
    PARTICIPATION, HISTORICAL_DEPENDENCE, CREATION, MANIFESTATION, BRINGS_ABOUT, TRIGGERS, COMPOSITION, 
    AGGREGATION, INHERENCE, VALUE, FORMAL, CONSTITUTION, 

    NUMBER_LITERAL, ESPECIAL_SYMBOL, NEW_TYPE, INSTANCE_NAME, CLASS_NAME, RELATION_NAME
};


// Token
struct token {
    uint type;
    string lexeme;
    int line;
    int column;
};